//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.235
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2011/8/9 16:29:56
namespace WCFClient.SchedulerDBEntities
{
    
    /// <summary>
    /// 架构中不存在 SchedulerDBEntities 的注释。
    /// </summary>
    public partial class SchedulerDBEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 SchedulerDBEntities 对象。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SchedulerDBEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("SchedulerDBModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WCFClient.SchedulerDBEntities", typeName.Substring(16)), false);
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WCFClient.SchedulerDBEntities", global::System.StringComparison.Ordinal))
            {
                return string.Concat("SchedulerDBModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 Appointments 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Appointments> Appointments
        {
            get
            {
                if ((this._Appointments == null))
                {
                    this._Appointments = base.CreateQuery<Appointments>("Appointments");
                }
                return this._Appointments;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Appointments> _Appointments;
        /// <summary>
        /// 架构中不存在 Rooms 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Rooms> Rooms
        {
            get
            {
                if ((this._Rooms == null))
                {
                    this._Rooms = base.CreateQuery<Rooms>("Rooms");
                }
                return this._Rooms;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Rooms> _Rooms;
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("Users");
                }
                return this._Users;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Users> _Users;
        /// <summary>
        /// 架构中不存在 Appointments 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAppointments(Appointments appointments)
        {
            base.AddObject("Appointments", appointments);
        }
        /// <summary>
        /// 架构中不存在 Rooms 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRooms(Rooms rooms)
        {
            base.AddObject("Rooms", rooms);
        }
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    }
    /// <summary>
    /// 架构中不存在 SchedulerDBModel.Appointments 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Appointments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Appointments : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 Appointments 对象。
        /// </summary>
        /// <param name="ID">ID 的初始值。</param>
        /// <param name="subject">Subject 的初始值。</param>
        /// <param name="start">Start 的初始值。</param>
        /// <param name="end">End 的初始值。</param>
        /// <param name="iD2">ID2 的初始值。</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Appointments CreateAppointments(global::System.Guid ID, string subject, global::System.DateTime start, global::System.DateTime end, long iD2)
        {
            Appointments appointments = new Appointments();
            appointments.ID = ID;
            appointments.Subject = subject;
            appointments.Start = start;
            appointments.End = end;
            appointments.ID2 = iD2;
            return appointments;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 Subject 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
                this.OnPropertyChanged("Subject");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 Start 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Start
        {
            get
            {
                return this._Start;
            }
            set
            {
                this.OnStartChanging(value);
                this._Start = value;
                this.OnStartChanged();
                this.OnPropertyChanged("Start");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
        /// <summary>
        /// 架构中不存在属性 End 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime End
        {
            get
            {
                return this._End;
            }
            set
            {
                this.OnEndChanging(value);
                this._End = value;
                this.OnEndChanged();
                this.OnPropertyChanged("End");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
        /// <summary>
        /// 架构中不存在属性 RoomID 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> RoomID
        {
            get
            {
                return this._RoomID;
            }
            set
            {
                this.OnRoomIDChanging(value);
                this._RoomID = value;
                this.OnRoomIDChanged();
                this.OnPropertyChanged("RoomID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _RoomID;
        partial void OnRoomIDChanging(global::System.Nullable<int> value);
        partial void OnRoomIDChanged();
        /// <summary>
        /// 架构中不存在属性 UserID 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                this._UserID = value;
                this.OnUserIDChanged();
                this.OnPropertyChanged("UserID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _UserID;
        partial void OnUserIDChanging(global::System.Nullable<int> value);
        partial void OnUserIDChanged();
        /// <summary>
        /// 架构中不存在属性 RecurrenceRule 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RecurrenceRule
        {
            get
            {
                return this._RecurrenceRule;
            }
            set
            {
                this.OnRecurrenceRuleChanging(value);
                this._RecurrenceRule = value;
                this.OnRecurrenceRuleChanged();
                this.OnPropertyChanged("RecurrenceRule");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RecurrenceRule;
        partial void OnRecurrenceRuleChanging(string value);
        partial void OnRecurrenceRuleChanged();
        /// <summary>
        /// 架构中不存在属性 RecurrenceParentID 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> RecurrenceParentID
        {
            get
            {
                return this._RecurrenceParentID;
            }
            set
            {
                this.OnRecurrenceParentIDChanging(value);
                this._RecurrenceParentID = value;
                this.OnRecurrenceParentIDChanged();
                this.OnPropertyChanged("RecurrenceParentID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _RecurrenceParentID;
        partial void OnRecurrenceParentIDChanging(global::System.Nullable<int> value);
        partial void OnRecurrenceParentIDChanged();
        /// <summary>
        /// 架构中不存在属性 Reminder 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reminder
        {
            get
            {
                return this._Reminder;
            }
            set
            {
                this.OnReminderChanging(value);
                this._Reminder = value;
                this.OnReminderChanged();
                this.OnPropertyChanged("Reminder");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reminder;
        partial void OnReminderChanging(string value);
        partial void OnReminderChanged();
        /// <summary>
        /// 架构中不存在属性 Annotations 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Annotations
        {
            get
            {
                return this._Annotations;
            }
            set
            {
                this.OnAnnotationsChanging(value);
                this._Annotations = value;
                this.OnAnnotationsChanged();
                this.OnPropertyChanged("Annotations");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Annotations;
        partial void OnAnnotationsChanging(string value);
        partial void OnAnnotationsChanged();
        /// <summary>
        /// 架构中不存在属性 ID2 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long ID2
        {
            get
            {
                return this._ID2;
            }
            set
            {
                this.OnID2Changing(value);
                this._ID2 = value;
                this.OnID2Changed();
                this.OnPropertyChanged("ID2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _ID2;
        partial void OnID2Changing(long value);
        partial void OnID2Changed();
        /// <summary>
        /// 架构中不存在 Rooms 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Rooms Rooms
        {
            get
            {
                return this._Rooms;
            }
            set
            {
                this._Rooms = value;
                this.OnPropertyChanged("Rooms");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Rooms _Rooms;
        /// <summary>
        /// 架构中不存在 Users 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Users Users
        {
            get
            {
                return this._Users;
            }
            set
            {
                this._Users = value;
                this.OnPropertyChanged("Users");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Users _Users;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 SchedulerDBModel.Rooms 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Rooms")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Rooms : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 Rooms 对象。
        /// </summary>
        /// <param name="ID">ID 的初始值。</param>
        /// <param name="roomName">RoomName 的初始值。</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Rooms CreateRooms(int ID, string roomName)
        {
            Rooms rooms = new Rooms();
            rooms.ID = ID;
            rooms.RoomName = roomName;
            return rooms;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 RoomName 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RoomName
        {
            get
            {
                return this._RoomName;
            }
            set
            {
                this.OnRoomNameChanging(value);
                this._RoomName = value;
                this.OnRoomNameChanged();
                this.OnPropertyChanged("RoomName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RoomName;
        partial void OnRoomNameChanging(string value);
        partial void OnRoomNameChanged();
        /// <summary>
        /// 架构中不存在 Appointments 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Appointments> Appointments
        {
            get
            {
                return this._Appointments;
            }
            set
            {
                this._Appointments = value;
                this.OnPropertyChanged("Appointments");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Appointments> _Appointments = new global::System.Data.Services.Client.DataServiceCollection<Appointments>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 SchedulerDBModel.Users 的注释。
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Users : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 Users 对象。
        /// </summary>
        /// <param name="ID">ID 的初始值。</param>
        /// <param name="userName">UserName 的初始值。</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Users CreateUsers(int ID, string userName)
        {
            Users users = new Users();
            users.ID = ID;
            users.UserName = userName;
            return users;
        }
        /// <summary>
        /// 架构中不存在属性 ID 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// 架构中不存在属性 UserName 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// 架构中不存在 Appointments 的注释。
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Appointments> Appointments
        {
            get
            {
                return this._Appointments;
            }
            set
            {
                this._Appointments = value;
                this.OnPropertyChanged("Appointments");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Appointments> _Appointments = new global::System.Data.Services.Client.DataServiceCollection<Appointments>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
