//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace UTPWCFDataService
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class UTPDataEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“UTPDataEntities”部分中的连接字符串初始化新 UTPDataEntities 对象。
        /// </summary>
        public UTPDataEntities() : base("name=UTPDataEntities", "UTPDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 UTPDataEntities 对象。
        /// </summary>
        public UTPDataEntities(string connectionString) : base(connectionString, "UTPDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 UTPDataEntities 对象。
        /// </summary>
        public UTPDataEntities(EntityConnection connection) : base(connection, "UTPDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<View_CustomerInformation> View_CustomerInformation
        {
            get
            {
                if ((_View_CustomerInformation == null))
                {
                    _View_CustomerInformation = base.CreateObjectSet<View_CustomerInformation>("View_CustomerInformation");
                }
                return _View_CustomerInformation;
            }
        }
        private ObjectSet<View_CustomerInformation> _View_CustomerInformation;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 View_CustomerInformation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToView_CustomerInformation(View_CustomerInformation view_CustomerInformation)
        {
            base.AddObject("View_CustomerInformation", view_CustomerInformation);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UTPModel", Name="View_CustomerInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class View_CustomerInformation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 View_CustomerInformation 对象。
        /// </summary>
        /// <param name="acctNum">AcctNum 属性的初始值。</param>
        /// <param name="customerID">CustomerID 属性的初始值。</param>
        /// <param name="firstName">FirstName 属性的初始值。</param>
        /// <param name="lastName">LastName 属性的初始值。</param>
        public static View_CustomerInformation CreateView_CustomerInformation(global::System.String acctNum, global::System.String customerID, global::System.String firstName, global::System.String lastName)
        {
            View_CustomerInformation view_CustomerInformation = new View_CustomerInformation();
            view_CustomerInformation.AcctNum = acctNum;
            view_CustomerInformation.CustomerID = customerID;
            view_CustomerInformation.FirstName = firstName;
            view_CustomerInformation.LastName = lastName;
            return view_CustomerInformation;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AcctNum
        {
            get
            {
                return _AcctNum;
            }
            set
            {
                if (_AcctNum != value)
                {
                    OnAcctNumChanging(value);
                    ReportPropertyChanging("AcctNum");
                    _AcctNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AcctNum");
                    OnAcctNumChanged();
                }
            }
        }
        private global::System.String _AcctNum;
        partial void OnAcctNumChanging(global::System.String value);
        partial void OnAcctNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.String _CustomerID;
        partial void OnCustomerIDChanging(global::System.String value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                if (_FirstName != value)
                {
                    OnFirstNameChanging(value);
                    ReportPropertyChanging("FirstName");
                    _FirstName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FirstName");
                    OnFirstNameChanged();
                }
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                if (_LastName != value)
                {
                    OnLastNameChanging(value);
                    ReportPropertyChanging("LastName");
                    _LastName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LastName");
                    OnLastNameChanged();
                }
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrDue
        {
            get
            {
                return _CurrDue;
            }
            set
            {
                OnCurrDueChanging(value);
                ReportPropertyChanging("CurrDue");
                _CurrDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrDue");
                OnCurrDueChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrDue;
        partial void OnCurrDueChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrDueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalDue
        {
            get
            {
                return _TotalDue;
            }
            set
            {
                OnTotalDueChanging(value);
                ReportPropertyChanging("TotalDue");
                _TotalDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalDue");
                OnTotalDueChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalDue;
        partial void OnTotalDueChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalDueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillDate
        {
            get
            {
                return _BillDate;
            }
            set
            {
                OnBillDateChanging(value);
                ReportPropertyChanging("BillDate");
                _BillDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BillDate");
                OnBillDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillDate;
        partial void OnBillDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBillDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BillAmt
        {
            get
            {
                return _BillAmt;
            }
            set
            {
                OnBillAmtChanging(value);
                ReportPropertyChanging("BillAmt");
                _BillAmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BillAmt");
                OnBillAmtChanged();
            }
        }
        private Nullable<global::System.Decimal> _BillAmt;
        partial void OnBillAmtChanging(Nullable<global::System.Decimal> value);
        partial void OnBillAmtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
    }

    #endregion
    
}
