//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ChartDemo
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MECEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MECEntities”部分中的连接字符串初始化新 MECEntities 对象。
        /// </summary>
        public MECEntities() : base("name=MECEntities", "MECEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MECEntities 对象。
        /// </summary>
        public MECEntities(string connectionString) : base(connectionString, "MECEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MECEntities 对象。
        /// </summary>
        public MECEntities(EntityConnection connection) : base(connection, "MECEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ViewBillHistory> ViewBillHistory
        {
            get
            {
                if ((_ViewBillHistory == null))
                {
                    _ViewBillHistory = base.CreateObjectSet<ViewBillHistory>("ViewBillHistory");
                }
                return _ViewBillHistory;
            }
        }
        private ObjectSet<ViewBillHistory> _ViewBillHistory;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ViewUsageHistory> ViewUsageHistory
        {
            get
            {
                if ((_ViewUsageHistory == null))
                {
                    _ViewUsageHistory = base.CreateObjectSet<ViewUsageHistory>("ViewUsageHistory");
                }
                return _ViewUsageHistory;
            }
        }
        private ObjectSet<ViewUsageHistory> _ViewUsageHistory;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 ViewBillHistory EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToViewBillHistory(ViewBillHistory viewBillHistory)
        {
            base.AddObject("ViewBillHistory", viewBillHistory);
        }
    
        /// <summary>
        /// 用于向 ViewUsageHistory EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToViewUsageHistory(ViewUsageHistory viewUsageHistory)
        {
            base.AddObject("ViewUsageHistory", viewUsageHistory);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MECModel", Name="ViewBillHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewBillHistory : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ViewBillHistory 对象。
        /// </summary>
        /// <param name="acctNum">AcctNum 属性的初始值。</param>
        /// <param name="customerID">CustomerID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="address">Address 属性的初始值。</param>
        /// <param name="location">Location 属性的初始值。</param>
        /// <param name="amount">Amount 属性的初始值。</param>
        public static ViewBillHistory CreateViewBillHistory(global::System.String acctNum, global::System.String customerID, global::System.String name, global::System.String address, global::System.String location, global::System.Decimal amount)
        {
            ViewBillHistory viewBillHistory = new ViewBillHistory();
            viewBillHistory.AcctNum = acctNum;
            viewBillHistory.CustomerID = customerID;
            viewBillHistory.Name = name;
            viewBillHistory.Address = address;
            viewBillHistory.Location = location;
            viewBillHistory.Amount = amount;
            return viewBillHistory;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comp
        {
            get
            {
                return _Comp;
            }
            set
            {
                OnCompChanging(value);
                ReportPropertyChanging("Comp");
                _Comp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comp");
                OnCompChanged();
            }
        }
        private global::System.String _Comp;
        partial void OnCompChanging(global::System.String value);
        partial void OnCompChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Cycle
        {
            get
            {
                return _Cycle;
            }
            set
            {
                OnCycleChanging(value);
                ReportPropertyChanging("Cycle");
                _Cycle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cycle");
                OnCycleChanged();
            }
        }
        private Nullable<global::System.Int16> _Cycle;
        partial void OnCycleChanging(Nullable<global::System.Int16> value);
        partial void OnCycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AcctNum
        {
            get
            {
                return _AcctNum;
            }
            set
            {
                if (_AcctNum != value)
                {
                    OnAcctNumChanging(value);
                    ReportPropertyChanging("AcctNum");
                    _AcctNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AcctNum");
                    OnAcctNumChanged();
                }
            }
        }
        private global::System.String _AcctNum;
        partial void OnAcctNumChanging(global::System.String value);
        partial void OnAcctNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.String _CustomerID;
        partial void OnCustomerIDChanging(global::System.String value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalDue
        {
            get
            {
                return _TotalDue;
            }
            set
            {
                OnTotalDueChanging(value);
                ReportPropertyChanging("TotalDue");
                _TotalDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalDue");
                OnTotalDueChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalDue;
        partial void OnTotalDueChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalDueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrDue
        {
            get
            {
                return _CurrDue;
            }
            set
            {
                OnCurrDueChanging(value);
                ReportPropertyChanging("CurrDue");
                _CurrDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrDue");
                OnCurrDueChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrDue;
        partial void OnCurrDueChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrDueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Past1
        {
            get
            {
                return _Past1;
            }
            set
            {
                OnPast1Changing(value);
                ReportPropertyChanging("Past1");
                _Past1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Past1");
                OnPast1Changed();
            }
        }
        private Nullable<global::System.Decimal> _Past1;
        partial void OnPast1Changing(Nullable<global::System.Decimal> value);
        partial void OnPast1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Past2
        {
            get
            {
                return _Past2;
            }
            set
            {
                OnPast2Changing(value);
                ReportPropertyChanging("Past2");
                _Past2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Past2");
                OnPast2Changed();
            }
        }
        private Nullable<global::System.Decimal> _Past2;
        partial void OnPast2Changing(Nullable<global::System.Decimal> value);
        partial void OnPast2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Past3
        {
            get
            {
                return _Past3;
            }
            set
            {
                OnPast3Changing(value);
                ReportPropertyChanging("Past3");
                _Past3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Past3");
                OnPast3Changed();
            }
        }
        private Nullable<global::System.Decimal> _Past3;
        partial void OnPast3Changing(Nullable<global::System.Decimal> value);
        partial void OnPast3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                if (_Address != value)
                {
                    OnAddressChanging(value);
                    ReportPropertyChanging("Address");
                    _Address = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                if (_Location != value)
                {
                    OnLocationChanging(value);
                    ReportPropertyChanging("Location");
                    _Location = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Location");
                    OnLocationChanged();
                }
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if (_Amount != value)
                {
                    OnAmountChanging(value);
                    ReportPropertyChanging("Amount");
                    _Amount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Amount");
                    OnAmountChanged();
                }
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LateCharge
        {
            get
            {
                return _LateCharge;
            }
            set
            {
                OnLateChargeChanging(value);
                ReportPropertyChanging("LateCharge");
                _LateCharge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LateCharge");
                OnLateChargeChanged();
            }
        }
        private Nullable<global::System.Decimal> _LateCharge;
        partial void OnLateChargeChanging(Nullable<global::System.Decimal> value);
        partial void OnLateChargeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TransactionDate
        {
            get
            {
                return _TransactionDate;
            }
            set
            {
                OnTransactionDateChanging(value);
                ReportPropertyChanging("TransactionDate");
                _TransactionDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransactionDate");
                OnTransactionDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TransactionDate;
        partial void OnTransactionDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTransactionDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RevC
        {
            get
            {
                return _RevC;
            }
            set
            {
                OnRevCChanging(value);
                ReportPropertyChanging("RevC");
                _RevC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RevC");
                OnRevCChanged();
            }
        }
        private global::System.String _RevC;
        partial void OnRevCChanging(global::System.String value);
        partial void OnRevCChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RevenueType
        {
            get
            {
                return _RevenueType;
            }
            set
            {
                OnRevenueTypeChanging(value);
                ReportPropertyChanging("RevenueType");
                _RevenueType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RevenueType");
                OnRevenueTypeChanged();
            }
        }
        private global::System.String _RevenueType;
        partial void OnRevenueTypeChanging(global::System.String value);
        partial void OnRevenueTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GLBatchNum
        {
            get
            {
                return _GLBatchNum;
            }
            set
            {
                OnGLBatchNumChanging(value);
                ReportPropertyChanging("GLBatchNum");
                _GLBatchNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GLBatchNum");
                OnGLBatchNumChanged();
            }
        }
        private Nullable<global::System.Int32> _GLBatchNum;
        partial void OnGLBatchNumChanging(Nullable<global::System.Int32> value);
        partial void OnGLBatchNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GLBatchDate
        {
            get
            {
                return _GLBatchDate;
            }
            set
            {
                OnGLBatchDateChanging(value);
                ReportPropertyChanging("GLBatchDate");
                _GLBatchDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GLBatchDate");
                OnGLBatchDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GLBatchDate;
        partial void OnGLBatchDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGLBatchDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillNumberID
        {
            get
            {
                return _BillNumberID;
            }
            set
            {
                OnBillNumberIDChanging(value);
                ReportPropertyChanging("BillNumberID");
                _BillNumberID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillNumberID");
                OnBillNumberIDChanged();
            }
        }
        private global::System.String _BillNumberID;
        partial void OnBillNumberIDChanging(global::System.String value);
        partial void OnBillNumberIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MECModel", Name="ViewUsageHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewUsageHistory : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ViewUsageHistory 对象。
        /// </summary>
        /// <param name="acctNum">AcctNum 属性的初始值。</param>
        /// <param name="customerID">CustomerID 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="address">Address 属性的初始值。</param>
        /// <param name="location">Location 属性的初始值。</param>
        /// <param name="isEst">IsEst 属性的初始值。</param>
        public static ViewUsageHistory CreateViewUsageHistory(global::System.String acctNum, global::System.String customerID, global::System.String name, global::System.String address, global::System.String location, global::System.String isEst)
        {
            ViewUsageHistory viewUsageHistory = new ViewUsageHistory();
            viewUsageHistory.AcctNum = acctNum;
            viewUsageHistory.CustomerID = customerID;
            viewUsageHistory.Name = name;
            viewUsageHistory.Address = address;
            viewUsageHistory.Location = location;
            viewUsageHistory.IsEst = isEst;
            return viewUsageHistory;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comp
        {
            get
            {
                return _Comp;
            }
            set
            {
                OnCompChanging(value);
                ReportPropertyChanging("Comp");
                _Comp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comp");
                OnCompChanged();
            }
        }
        private global::System.String _Comp;
        partial void OnCompChanging(global::System.String value);
        partial void OnCompChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Cycle
        {
            get
            {
                return _Cycle;
            }
            set
            {
                OnCycleChanging(value);
                ReportPropertyChanging("Cycle");
                _Cycle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cycle");
                OnCycleChanged();
            }
        }
        private Nullable<global::System.Int16> _Cycle;
        partial void OnCycleChanging(Nullable<global::System.Int16> value);
        partial void OnCycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AcctNum
        {
            get
            {
                return _AcctNum;
            }
            set
            {
                if (_AcctNum != value)
                {
                    OnAcctNumChanging(value);
                    ReportPropertyChanging("AcctNum");
                    _AcctNum = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AcctNum");
                    OnAcctNumChanged();
                }
            }
        }
        private global::System.String _AcctNum;
        partial void OnAcctNumChanging(global::System.String value);
        partial void OnAcctNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.String _CustomerID;
        partial void OnCustomerIDChanging(global::System.String value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalDue
        {
            get
            {
                return _TotalDue;
            }
            set
            {
                OnTotalDueChanging(value);
                ReportPropertyChanging("TotalDue");
                _TotalDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalDue");
                OnTotalDueChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalDue;
        partial void OnTotalDueChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalDueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrDue
        {
            get
            {
                return _CurrDue;
            }
            set
            {
                OnCurrDueChanging(value);
                ReportPropertyChanging("CurrDue");
                _CurrDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrDue");
                OnCurrDueChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrDue;
        partial void OnCurrDueChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrDueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Past1
        {
            get
            {
                return _Past1;
            }
            set
            {
                OnPast1Changing(value);
                ReportPropertyChanging("Past1");
                _Past1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Past1");
                OnPast1Changed();
            }
        }
        private Nullable<global::System.Decimal> _Past1;
        partial void OnPast1Changing(Nullable<global::System.Decimal> value);
        partial void OnPast1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Past2
        {
            get
            {
                return _Past2;
            }
            set
            {
                OnPast2Changing(value);
                ReportPropertyChanging("Past2");
                _Past2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Past2");
                OnPast2Changed();
            }
        }
        private Nullable<global::System.Decimal> _Past2;
        partial void OnPast2Changing(Nullable<global::System.Decimal> value);
        partial void OnPast2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Past3
        {
            get
            {
                return _Past3;
            }
            set
            {
                OnPast3Changing(value);
                ReportPropertyChanging("Past3");
                _Past3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Past3");
                OnPast3Changed();
            }
        }
        private Nullable<global::System.Decimal> _Past3;
        partial void OnPast3Changing(Nullable<global::System.Decimal> value);
        partial void OnPast3Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                if (_Address != value)
                {
                    OnAddressChanging(value);
                    ReportPropertyChanging("Address");
                    _Address = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                if (_Location != value)
                {
                    OnLocationChanging(value);
                    ReportPropertyChanging("Location");
                    _Location = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Location");
                    OnLocationChanged();
                }
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReadDt
        {
            get
            {
                return _ReadDt;
            }
            set
            {
                OnReadDtChanging(value);
                ReportPropertyChanging("ReadDt");
                _ReadDt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadDt");
                OnReadDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReadDt;
        partial void OnReadDtChanging(Nullable<global::System.DateTime> value);
        partial void OnReadDtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BillDt
        {
            get
            {
                return _BillDt;
            }
            set
            {
                OnBillDtChanging(value);
                ReportPropertyChanging("BillDt");
                _BillDt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BillDt");
                OnBillDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _BillDt;
        partial void OnBillDtChanging(Nullable<global::System.DateTime> value);
        partial void OnBillDtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MeterAccount
        {
            get
            {
                return _MeterAccount;
            }
            set
            {
                OnMeterAccountChanging(value);
                ReportPropertyChanging("MeterAccount");
                _MeterAccount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MeterAccount");
                OnMeterAccountChanged();
            }
        }
        private global::System.String _MeterAccount;
        partial void OnMeterAccountChanging(global::System.String value);
        partial void OnMeterAccountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PartPeakRead
        {
            get
            {
                return _PartPeakRead;
            }
            set
            {
                OnPartPeakReadChanging(value);
                ReportPropertyChanging("PartPeakRead");
                _PartPeakRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartPeakRead");
                OnPartPeakReadChanged();
            }
        }
        private Nullable<global::System.Double> _PartPeakRead;
        partial void OnPartPeakReadChanging(Nullable<global::System.Double> value);
        partial void OnPartPeakReadChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PartPeakUsage
        {
            get
            {
                return _PartPeakUsage;
            }
            set
            {
                OnPartPeakUsageChanging(value);
                ReportPropertyChanging("PartPeakUsage");
                _PartPeakUsage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartPeakUsage");
                OnPartPeakUsageChanged();
            }
        }
        private Nullable<global::System.Double> _PartPeakUsage;
        partial void OnPartPeakUsageChanging(Nullable<global::System.Double> value);
        partial void OnPartPeakUsageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> UsageChrg
        {
            get
            {
                return _UsageChrg;
            }
            set
            {
                OnUsageChrgChanging(value);
                ReportPropertyChanging("UsageChrg");
                _UsageChrg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsageChrg");
                OnUsageChrgChanged();
            }
        }
        private Nullable<global::System.Double> _UsageChrg;
        partial void OnUsageChrgChanging(Nullable<global::System.Double> value);
        partial void OnUsageChrgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IsEst
        {
            get
            {
                return _IsEst;
            }
            set
            {
                if (_IsEst != value)
                {
                    OnIsEstChanging(value);
                    ReportPropertyChanging("IsEst");
                    _IsEst = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IsEst");
                    OnIsEstChanged();
                }
            }
        }
        private global::System.String _IsEst;
        partial void OnIsEstChanging(global::System.String value);
        partial void OnIsEstChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UtilType
        {
            get
            {
                return _UtilType;
            }
            set
            {
                OnUtilTypeChanging(value);
                ReportPropertyChanging("UtilType");
                _UtilType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UtilType");
                OnUtilTypeChanged();
            }
        }
        private global::System.String _UtilType;
        partial void OnUtilTypeChanging(global::System.String value);
        partial void OnUtilTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UsageRate
        {
            get
            {
                return _UsageRate;
            }
            set
            {
                OnUsageRateChanging(value);
                ReportPropertyChanging("UsageRate");
                _UsageRate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UsageRate");
                OnUsageRateChanged();
            }
        }
        private global::System.String _UsageRate;
        partial void OnUsageRateChanging(global::System.String value);
        partial void OnUsageRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PremiseID
        {
            get
            {
                return _PremiseID;
            }
            set
            {
                OnPremiseIDChanging(value);
                ReportPropertyChanging("PremiseID");
                _PremiseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PremiseID");
                OnPremiseIDChanged();
            }
        }
        private global::System.String _PremiseID;
        partial void OnPremiseIDChanging(global::System.String value);
        partial void OnPremiseIDChanged();

        #endregion
    
    }

    #endregion
    
}
