//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WCF_Demo
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class WCFDemoDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“WCFDemoDBEntities”部分中的连接字符串初始化新 WCFDemoDBEntities 对象。
        /// </summary>
        public WCFDemoDBEntities() : base("name=WCFDemoDBEntities", "WCFDemoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 WCFDemoDBEntities 对象。
        /// </summary>
        public WCFDemoDBEntities(string connectionString) : base(connectionString, "WCFDemoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 WCFDemoDBEntities 对象。
        /// </summary>
        public WCFDemoDBEntities(EntityConnection connection) : base(connection, "WCFDemoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UtilityCompany> UtilityCompany
        {
            get
            {
                if ((_UtilityCompany == null))
                {
                    _UtilityCompany = base.CreateObjectSet<UtilityCompany>("UtilityCompany");
                }
                return _UtilityCompany;
            }
        }
        private ObjectSet<UtilityCompany> _UtilityCompany;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 UtilityCompany EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUtilityCompany(UtilityCompany utilityCompany)
        {
            base.AddObject("UtilityCompany", utilityCompany);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WCFDemoDBModel", Name="UtilityCompany")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UtilityCompany : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UtilityCompany 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static UtilityCompany CreateUtilityCompany(global::System.Guid id)
        {
            UtilityCompany utilityCompany = new UtilityCompany();
            utilityCompany.ID = id;
            return utilityCompany;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WCFUri
        {
            get
            {
                return _WCFUri;
            }
            set
            {
                OnWCFUriChanging(value);
                ReportPropertyChanging("WCFUri");
                _WCFUri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WCFUri");
                OnWCFUriChanged();
            }
        }
        private global::System.String _WCFUri;
        partial void OnWCFUriChanging(global::System.String value);
        partial void OnWCFUriChanged();

        #endregion
    
    }

    #endregion
    
}
