//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.IIS_Hosting_Without_SVC_File_ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IIS_Hosting_Without_SVC_File_ServiceReference.IDemo")]
    public interface IDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemo/Hello", ReplyAction="http://tempuri.org/IDemo/HelloResponse")]
        string Hello(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoChannel : WebClient.IIS_Hosting_Without_SVC_File_ServiceReference.IDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoClient : System.ServiceModel.ClientBase<WebClient.IIS_Hosting_Without_SVC_File_ServiceReference.IDemo>, WebClient.IIS_Hosting_Without_SVC_File_ServiceReference.IDemo {
        
        public DemoClient() {
        }
        
        public DemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello(string name) {
            return base.Channel.Hello(name);
        }
    }
}
