//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.en_US", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The new password is required! 的本地化字符串。
        /// </summary>
        internal static string ChangePassword_rfvNewPasswork_Text {
            get {
                return ResourceManager.GetString("ChangePassword_rfvNewPasswork_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        internal static string Home_lblConfirmPassword_Text {
            get {
                return ResourceManager.GetString("Home_lblConfirmPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        internal static string Home_lblNewPasswork_Text {
            get {
                return ResourceManager.GetString("Home_lblNewPasswork_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Home_rbtnCancel_Text {
            get {
                return ResourceManager.GetString("Home_rbtnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Home_rbtnSave_Text {
            get {
                return ResourceManager.GetString("Home_rbtnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string Home_WindowsFieldSet_Title {
            get {
                return ResourceManager.GetString("Home_WindowsFieldSet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Service Direct Account 的本地化字符串。
        /// </summary>
        internal static string Logon_lblLoginTitle_Text {
            get {
                return ResourceManager.GetString("Logon_lblLoginTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Logon_lblPassword_Text {
            get {
                return ResourceManager.GetString("Logon_lblPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User ID 的本地化字符串。
        /// </summary>
        internal static string Logon_lblUserName_Text {
            get {
                return ResourceManager.GetString("Logon_lblUserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The User ID or the Password is wrong! 的本地化字符串。
        /// </summary>
        internal static string Logon_LoginError_Text {
            get {
                return ResourceManager.GetString("Logon_LoginError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is requireded! 的本地化字符串。
        /// </summary>
        internal static string Logon_PasswordResquest_Text {
            get {
                return ResourceManager.GetString("Logon_PasswordResquest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User or password must be resquest! 的本地化字符串。
        /// </summary>
        internal static string Logon_txtEmpty_Text {
            get {
                return ResourceManager.GetString("Logon_txtEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User ID is requireded! 的本地化字符串。
        /// </summary>
        internal static string Logon_UserIDRequest_Text {
            get {
                return ResourceManager.GetString("Logon_UserIDRequest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created Date 的本地化字符串。
        /// </summary>
        internal static string RoleManagerForm_CreatedDate_HeaderText {
            get {
                return ResourceManager.GetString("RoleManagerForm_CreatedDate_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not be deleted! 的本地化字符串。
        /// </summary>
        internal static string RoleManagerForm_DeleteInfo {
            get {
                return ResourceManager.GetString("RoleManagerForm_DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string RoleManagerForm_Description_HeaderText {
            get {
                return ResourceManager.GetString("RoleManagerForm_Description_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Code 的本地化字符串。
        /// </summary>
        internal static string RoleManagerForm_RoleCode_HeaderText {
            get {
                return ResourceManager.GetString("RoleManagerForm_RoleCode_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Name 的本地化字符串。
        /// </summary>
        internal static string RoleManagerForm_RoleName_HeaderText {
            get {
                return ResourceManager.GetString("RoleManagerForm_RoleName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string RoleManagerForm_State_HeaderText {
            get {
                return ResourceManager.GetString("RoleManagerForm_State_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Site_DefaultSkin_Value {
            get {
                return ResourceManager.GetString("Site_DefaultSkin_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created Date 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_CreatedDate_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_CreatedDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Login Password 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblConfirmLoginPwd_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_lblConfirmLoginPwd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current user can not be deleted! 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblDesc_DeleteInfo {
            get {
                return ResourceManager.GetString("UserManagerForm_lblDesc_DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin Can&apos;t be deleted! 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblDesc_DeleteInfoAdmin {
            get {
                return ResourceManager.GetString("UserManagerForm_lblDesc_DeleteInfoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblDesc_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_lblDesc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Error 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblEmailError_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_lblEmailError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblEmail_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_lblEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Name 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_LblLoginName_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_LblLoginName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblRole_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_lblRole_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_lblState_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_lblState_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Password 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_LoginPwd_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_LoginPwd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is the required item. 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_Req_Empty_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_Req_Empty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The confirm password is required! 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_rtxtConfirmPassword {
            get {
                return ResourceManager.GetString("UserManagerForm_rtxtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The passwords do not match, please try again. 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_ThePasswordsDoNotMatch_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_ThePasswordsDoNotMatch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Code 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_UserCode_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_UserCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string UserManagerForm_UserName_Text {
            get {
                return ResourceManager.GetString("UserManagerForm_UserName_Text", resourceCulture);
            }
        }
    }
}
