//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client2.MessageSvc.DuplexReentrant {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageSvc.DuplexReentrant.IDuplexReentrant", CallbackContract=typeof(Client2.MessageSvc.DuplexReentrant.IDuplexReentrantCallback))]
    public interface IDuplexReentrant {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexReentrant/HelloDuplexReentrant", ReplyAction="http://tempuri.org/IDuplexReentrant/HelloDuplexReentrantResponse")]
        void HelloDuplexReentrant(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDuplexReentrantCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexReentrant/HelloDuplexReentrantCallback", ReplyAction="http://tempuri.org/IDuplexReentrant/HelloDuplexReentrantCallbackResponse")]
        void HelloDuplexReentrantCallback(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDuplexReentrantChannel : Client2.MessageSvc.DuplexReentrant.IDuplexReentrant, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DuplexReentrantClient : System.ServiceModel.DuplexClientBase<Client2.MessageSvc.DuplexReentrant.IDuplexReentrant>, Client2.MessageSvc.DuplexReentrant.IDuplexReentrant {
        
        public DuplexReentrantClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DuplexReentrantClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DuplexReentrantClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DuplexReentrantClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DuplexReentrantClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void HelloDuplexReentrant(string name) {
            base.Channel.HelloDuplexReentrant(name);
        }
    }
}
