//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_btnCancel_text {
            get {
                return ResourceManager.GetString("BackupSettingForm_btnCancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_btnOK_text {
            get {
                return ResourceManager.GetString("BackupSettingForm_btnOK_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup folder : 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_lblBackupFolder_text {
            get {
                return ResourceManager.GetString("BackupSettingForm_lblBackupFolder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database name: 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_lblDatabase_text {
            get {
                return ResourceManager.GetString("BackupSettingForm_lblDatabase_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database server : 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_lblServer_text {
            get {
                return ResourceManager.GetString("BackupSettingForm_lblServer_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please complete required field. 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_rfvServer_ErrorMessage {
            get {
                return ResourceManager.GetString("BackupSettingForm_rfvServer_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create backupSetting failed. 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_SaveBackupMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("BackupSettingForm_SaveBackupMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update backupSetting failed. 的本地化字符串。
        /// </summary>
        internal static string BackupSettingForm_UpdateBackupMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("BackupSettingForm_UpdateBackupMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cycles you selected are invalid. 的本地化字符串。
        /// </summary>
        internal static string BillingForm_ConpanyCycle_Message {
            get {
                return ResourceManager.GetString("BillingForm_ConpanyCycle_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All cycles 的本地化字符串。
        /// </summary>
        internal static string BillingForm_lblAllCycles_text {
            get {
                return ResourceManager.GetString("BillingForm_lblAllCycles_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calc usage before billing register 的本地化字符串。
        /// </summary>
        internal static string BillingForm_lblCalc_text {
            get {
                return ResourceManager.GetString("BillingForm_lblCalc_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company 的本地化字符串。
        /// </summary>
        internal static string BillingForm_lblCompany_text {
            get {
                return ResourceManager.GetString("BillingForm_lblCompany_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billing shadow copies 的本地化字符串。
        /// </summary>
        internal static string BillingForm_lblcopy_text {
            get {
                return ResourceManager.GetString("BillingForm_lblcopy_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ending cycle 的本地化字符串。
        /// </summary>
        internal static string BillingForm_lblEndingCycle_text {
            get {
                return ResourceManager.GetString("BillingForm_lblEndingCycle_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting cycle 的本地化字符串。
        /// </summary>
        internal static string BillingForm_lblStartingCycle_text {
            get {
                return ResourceManager.GetString("BillingForm_lblStartingCycle_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status code 的本地化字符串。
        /// </summary>
        internal static string BillingForm_lblStatusCode_text {
            get {
                return ResourceManager.GetString("BillingForm_lblStatusCode_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string BillingForm_rbtnCancel_text {
            get {
                return ResourceManager.GetString("BillingForm_rbtnCancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string BillingForm_rbtnOK_text {
            get {
                return ResourceManager.GetString("BillingForm_rbtnOK_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save data failed! 的本地化字符串。
        /// </summary>
        internal static string BillingForm_SaveMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("BillingForm_SaveMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attention! Start Cycle must not be greater than End Cycle. 的本地化字符串。
        /// </summary>
        internal static string BillingForm_SelectCycleMessage_Message {
            get {
                return ResourceManager.GetString("BillingForm_SelectCycleMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_btnCancel_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_btnCancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_btnOK_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_btnOK_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save changes? 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_ConfirmPwd_ErrorMessage {
            get {
                return ResourceManager.GetString("EmailSettingForm_ConfirmPwd_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From : 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblFrom_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblFrom_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port : 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblPorts_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblPorts_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server name: 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblServerName_Text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblServerName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfirmPwd 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblSMTPConfirmPwd_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblSMTPConfirmPwd_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username : 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblSMTPName_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblSMTPName_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OldPwd 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblSMTPOldPwd_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblSMTPOldPwd_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password : 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblSMTPPwd_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblSMTPPwd_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL/TLS : 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblSSL_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblSSL_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To : 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_lblTo_text {
            get {
                return ResourceManager.GetString("EmailSettingForm_lblTo_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid email address. 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_revRegularFrom_ErrorMessage {
            get {
                return ResourceManager.GetString("EmailSettingForm_revRegularFrom_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please complete required field. 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_rfvRequiredFrom_ErrorMessage {
            get {
                return ResourceManager.GetString("EmailSettingForm_rfvRequiredFrom_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create emailSetting failed. 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_SaveEmailSetting_ErrorMessage {
            get {
                return ResourceManager.GetString("EmailSettingForm_SaveEmailSetting_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update emailSetting failed. 的本地化字符串。
        /// </summary>
        internal static string EmailSettingForm_UpdateEmailSetting_ErrorMessage {
            get {
                return ResourceManager.GetString("EmailSettingForm_UpdateEmailSetting_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module ID 的本地化字符串。
        /// </summary>
        internal static string ModuelIDForm_lblModuelId_text {
            get {
                return ResourceManager.GetString("ModuelIDForm_lblModuelId_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL 的本地化字符串。
        /// </summary>
        internal static string ModuelIDForm_lblURL_text {
            get {
                return ResourceManager.GetString("ModuelIDForm_lblURL_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string ModuelIDForm_rbtnCancel_text {
            get {
                return ResourceManager.GetString("ModuelIDForm_rbtnCancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string ModuelIDForm_rbtnOK_text {
            get {
                return ResourceManager.GetString("ModuelIDForm_rbtnOK_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access denied. 的本地化字符串。
        /// </summary>
        internal static string NoPermissionForm_lblNoPermission_text {
            get {
                return ResourceManager.GetString("NoPermissionForm_lblNoPermission_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schedule Billing 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string ScheduleLogForm_btnClose_text {
            get {
                return ResourceManager.GetString("ScheduleLogForm_btnClose_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task Name : 的本地化字符串。
        /// </summary>
        internal static string ScheduleLogForm_lblTaskName_Text {
            get {
                return ResourceManager.GetString("ScheduleLogForm_lblTaskName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name : 的本地化字符串。
        /// </summary>
        internal static string ScheduleLogForm_lblUserName_Text {
            get {
                return ResourceManager.GetString("ScheduleLogForm_lblUserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Date 的本地化字符串。
        /// </summary>
        internal static string ScheduleLogForm_RadGridLogDate_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleLogForm_RadGridLogDate_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string ScheduleLogForm_RadGridMessage_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleLogForm_RadGridMessage_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schedule Date 的本地化字符串。
        /// </summary>
        internal static string ScheduleLogForm_RadGridScheeduleDate_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleLogForm_RadGridScheeduleDate_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string ScheduleLogForm_RadGridSubject_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleLogForm_RadGridSubject_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create job failed. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_CreateJobMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_CreateJobMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job created successfully. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_CreateJob_Message {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_CreateJob_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change current job status 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_CustomerMessage_Message {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_CustomerMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete job failed. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_DeleteJobMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_DeleteJobMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete task failed. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_DeleteTasksMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_DeleteTasksMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job deleted successfully. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_DeleteTasksMessage_RightMessage {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_DeleteTasksMessage_RightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task status was updated successfully. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_EbleDisableTasksMessage_RightMessage {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_EbleDisableTasksMessage_RightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can no longer be managed by SD.  的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_JobExcepeciton_Message {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_JobExcepeciton_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The job does not exist. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_JobMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_JobMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_JobResult_FailValue {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_JobResult_FailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_JobResult_SuccessValue {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_JobResult_SuccessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Result 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_JobResult_value {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_JobResult_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete this task? 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridDelete_ConfirmText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridDelete_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridDelete_Text {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridName_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridName_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End time 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridStartTime_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridStartTime_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridStatus_Create {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridStatus_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridStatus_Disable {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridStatus_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridStatus_Enable {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridStatus_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start time 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridStatus_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridStatus_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridSubject_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridSubject_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridType_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridType_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to change current task status? 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridUpdate_ConfirmText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridUpdate_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridViewStatus_HeaderText {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridViewStatus_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_RadGridView_Text {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_RadGridView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Task 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_rbtnInsert_text {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_rbtnInsert_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update task status failed. 的本地化字符串。
        /// </summary>
        internal static string ScheduleTasksForm_UpdateFailed_ErrorMessage {
            get {
                return ResourceManager.GetString("ScheduleTasksForm_UpdateFailed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string TaskDetailFormView_btnCancel_text {
            get {
                return ResourceManager.GetString("TaskDetailFormView_btnCancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string TaskDetailFormView_btnConfirm_text {
            get {
                return ResourceManager.GetString("TaskDetailFormView_btnConfirm_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create job failed. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailFormView_ConfirmMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailFormView_ConfirmMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Start Time cannot be earier than current time. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailFormView_StartTime_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailFormView_StartTime_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update task failed. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailFormView_UpdateTask_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailFormView_UpdateTask_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: the scheduled task period you selected is greater than 24 hours, are you sure to keep current settings? 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_AllowedTimeMessage_Message {
            get {
                return ResourceManager.GetString("TaskDetailForm_AllowedTimeMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_btnCancel_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_btnCancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_btnEdit_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_btnEdit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_btnOK_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_btnOK_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup database before billing 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_chkBDBB_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_chkBDBB_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings for Backup must be completed. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_CookiesBackup_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailForm_CookiesBackup_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings for Mail/Backup/Action must be completed. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_CookiesMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailForm_CookiesMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action : 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lblAction_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_lblAction_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alert Action : 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lblPostAction_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_lblPostAction_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End date : 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lblROBTT_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_lblROBTT_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run only on these days : 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lblROOTD_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_lblROOTD_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schedule type : 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lblScheduleType_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_lblScheduleType_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start date : 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lblStartTime_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_lblStartTime_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task name : 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lblTaskName_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_lblTaskName_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This task already exists. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_lnkMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailForm_lnkMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_rbtnBackupSetting_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_rbtnBackupSetting_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_rbtnBillingSetting_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_rbtnBillingSetting_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_rbtnMailSetting_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_rbtnMailSetting_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Task 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_rbtnNewTask_text {
            get {
                return ResourceManager.GetString("TaskDetailForm_rbtnNewTask_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The scheduled task period you selected has been occupied by other tasks, please check task summary page for available time slots. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_rdEndTime_Message {
            get {
                return ResourceManager.GetString("TaskDetailForm_rdEndTime_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please complete required field. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_rfvRequiredFrom_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailForm_rfvRequiredFrom_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create tasks failed. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_SaveTasksMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailForm_SaveTasksMessage_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: the scheduled task period you selected is less than 1 hour, are you sure to keep current settings? 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_TimeMessage_Message {
            get {
                return ResourceManager.GetString("TaskDetailForm_TimeMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update tasks failed. 的本地化字符串。
        /// </summary>
        internal static string TaskDetailForm_UpdateTasksMessage_ErrorMessage {
            get {
                return ResourceManager.GetString("TaskDetailForm_UpdateTasksMessage_ErrorMessage", resourceCulture);
            }
        }
    }
}
