//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavigationPane.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NPR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NPR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavigationPane.Properties.NPR", typeof(NPR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use State Persistence feature, the control should have a Unique Identifier. Which is set by giving a Name to the control, since PersistId is deprecated and may be removed in future releases of dot net..
        /// </summary>
        internal static string Auto_State_No_Uid {
            get {
                return ResourceManager.GetString("Auto_State_No_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner should implement IMinimizeHelped.
        /// </summary>
        internal static string Error_MinimizeHelperOwner {
            get {
                return ResourceManager.GetString("Error_MinimizeHelperOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add or Remove Buttons.
        /// </summary>
        internal static string NavigationPane_AddRemoveCommand {
            get {
                return ResourceManager.GetString("NavigationPane_AddRemoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Pane.
        /// </summary>
        internal static string NavigationPane_BarTitle {
            get {
                return ResourceManager.GetString("NavigationPane_BarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to expand the Navigation Pane.
        /// </summary>
        internal static string NavigationPane_BarTooltip {
            get {
                return ResourceManager.GetString("NavigationPane_BarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure buttons.
        /// </summary>
        internal static string NavigationPane_ConfigureButtonToolTip {
            get {
                return ResourceManager.GetString("NavigationPane_ConfigureButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand the Navigation Pane.
        /// </summary>
        internal static string NavigationPane_ExpandToolTip {
            get {
                return ResourceManager.GetString("NavigationPane_ExpandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Fe_wer Buttons.
        /// </summary>
        internal static string NavigationPane_FewerCommand {
            get {
                return ResourceManager.GetString("NavigationPane_FewerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the Navigation Pane.
        /// </summary>
        internal static string NavigationPane_MinimizeToolTip {
            get {
                return ResourceManager.GetString("NavigationPane_MinimizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _More Buttons.
        /// </summary>
        internal static string NavigationPane_MoreCommand {
            get {
                return ResourceManager.GetString("NavigationPane_MoreCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new _Window.
        /// </summary>
        internal static string NavigationPane_NewWindowCommand {
            get {
                return ResourceManager.GetString("NavigationPane_NewWindowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na_vigation Pane Options....
        /// </summary>
        internal static string NavigationPane_OptionsCommand {
            get {
                return ResourceManager.GetString("NavigationPane_OptionsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to expand the Expander.
        /// </summary>
        internal static string NavigationPaneExpander_BarToolTip {
            get {
                return ResourceManager.GetString("NavigationPaneExpander_BarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand the Expander.
        /// </summary>
        internal static string NavigationPaneExpander_ExpandToolTip {
            get {
                return ResourceManager.GetString("NavigationPaneExpander_ExpandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the Expander.
        /// </summary>
        internal static string NavigationPaneExpander_MinimizeToolTip {
            get {
                return ResourceManager.GetString("NavigationPaneExpander_MinimizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string NavigationPaneExpander_Title {
            get {
                return ResourceManager.GetString("NavigationPaneExpander_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string String_Cancel {
            get {
                return ResourceManager.GetString("String_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string String_MoveDown {
            get {
                return ResourceManager.GetString("String_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string String_MoveUp {
            get {
                return ResourceManager.GetString("String_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string String_Ok {
            get {
                return ResourceManager.GetString("String_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dislay buttons in this order.
        /// </summary>
        internal static string String_OptionsDescription {
            get {
                return ResourceManager.GetString("String_OptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Pane Options.
        /// </summary>
        internal static string String_OptionsTitle {
            get {
                return ResourceManager.GetString("String_OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string String_Reset {
            get {
                return ResourceManager.GetString("String_Reset", resourceCulture);
            }
        }
    }
}
